# Imagen base de Python liviana
FROM python:3.13.3-slim

# Directorio donde se ejecutará la app dentro del contenedor
WORKDIR /app

# Copia tu archivo main.py al contenedor
COPY main.py /app/

# Comando que se ejecuta cuando el contenedor corre
CMD ["python", "main.py"]
